135a136,143
> # Path setup for eups 1.2.30 package.
> INCLUDE := $(CFITSIO_SHARED_DIR)/include $(CCFITS_DIR)/include $(CCFITS_DIR)/include/CCfits $(FFTW_DIR)/include $(IMSUPPORT_DIR)/include $(SWARP_DIR)/include
> LIBS = $(NRECIPES_DIR)/lib $(FFTW_DIR)/lib $(SWARP_DIR)/lib $(CFITSIO_SHARED_DIR)/lib
> TPIX_FITS := $(SWARP_DIR)/lib/fits/libfits.a
> FITSIO := -lcfitsio
> CCFITS := $(CCFITS_DIR)/lib/libCCfits.so
> WCS_C := $(SWARP_DIR)/lib/wcs/libwcs_c.a
> NR2 := $(NRECIPES_DIR)/lib/libpress2ndkr.a
168a177,178
> override CPPFLAGS += $(addprefix -L ,$(LIBS))
> override CFLAGS += $(addprefix -L ,$(LIBS))
259c269
< 	$(CPPC) -o $@ $^ -L$(DES_PREREQ)/lib $(WCS_C) $(TPIX_FITS) $(FITSIO) -lCCfits -lm
---
> 	$(CPPC) $(CFLAGS) -o $@ $^ -L$(DES_PREREQ)/lib $(WCS_C) $(TPIX_FITS) $(FITSIO) $(CCFITS) -lm
