#include "ImageMorphology.hh"

int DetectBleedTrails(Morph::ImageDataType *input_image,
		      Morph::ImageDataType *output_image,
		      Morph::MaskDataType *input_mask,
		      Morph::MaskDataType *output_mask,
		      Morph::IndexType Nx,
		      Morph::IndexType Ny,
		      std::vector<Morph::IndexType> &trail_struct,
		      std::vector<Morph::IndexType> &ground_struct,
		      Morph::MaskDataType TrailRejectionMask,
		      Morph::MaskDataType TrailExceptionMask,
		      Morph::MaskDataType GroundRejectionMask,
		      Morph::MaskDataType GroundExceptionMask,
		      Morph::MaskDataType TrailMask,
		      Morph::MaskDataType InterpMask,
		      Morph::IndexType trail_pix_limit,
		      double scalefactor=1.0,
		      bool interpolate = false,
		      std::ostream &Ostr=std::cout);

int DetectBleedTrailsInBoxes(Morph::ImageDataType *image,
			     Morph::ImageDataType *output_image,
			     Morph::MaskDataType *input_mask,
			     Morph::MaskDataType *output_mask,
			     Morph::IndexType Nx,
			     Morph::IndexType Ny,
			     std::vector<Morph::BoxType>   &boxes,
			     std::vector<Morph::StatType>  &box_stats,
			     std::vector<Morph::IndexType> &trail_struct,
			     Morph::MaskDataType TrailRejectionMask,
			     Morph::MaskDataType TrailExceptionMask,
			     Morph::MaskDataType ImageRejectionMask,
			     Morph::MaskDataType ImageExceptionMask,
			     Morph::MaskDataType TrailMask,
			     Morph::MaskDataType InterpMask,
			     Morph::MaskDataType StarMask,
			     Morph::IndexType trail_pix_limit,
			     double scalefactor,
			     double star_scalefactor,
			     bool interpolate,
			     std::ostream &Ostr);

int DetectBleedTrailsInBlobs(Morph::ImageDataType *image,
			     Morph::ImageDataType *output_image,
			     Morph::MaskDataType *input_mask,
			     Morph::MaskDataType *output_mask,
			     Morph::IndexType Nx,
			     Morph::IndexType Ny,
			     std::vector<std::vector<Morph::IndexType> >   &blobs,
			     std::vector<Morph::StatType>  &blob_stats,
			     std::vector<Morph::IndexType> &trail_struct,
			     Morph::MaskDataType TrailRejectionMask,
			     Morph::MaskDataType TrailExceptionMask,
			     Morph::MaskDataType ImageRejectionMask,
			     Morph::MaskDataType ImageExceptionMask,
			     Morph::MaskDataType TrailMask,
			     Morph::MaskDataType InterpMask,
			     Morph::MaskDataType StarMask,
			     Morph::IndexType trail_pix_limit,
			     double scalefactor,
			     double star_scalefactor,
			     bool interpolate,
			     std::ostream &Ostr);

